### PR TITLE
FC filters are now applied to the url as well

### PR DESCRIPTION
**Pull request by GreatDanton**

### CODE REVIEW

**Comment by laura-king** [comment]
When I set a filter, I am unable to reset the view via the brush icon meant to clear filters.

**Comment by laura-king** [comment]
Once the filter clearing is fixed, this looks good to me.

**Review by tangkong — COMMENTED** [review]
Perhaps a dumb question: is underscore.js included in our dependencies?  Or is it a dep of a dep that I'm unaware of?

**Comment by GreatDanton** [comment]
> Perhaps a dumb question: is underscore.js included in our dependencies? Or is it a dep of a dep that I'm unaware of?

I believe this comes from lodash, which is part of our dependencies: https://lodash.com/docs/4.17.15#isEmpty

**Review by laura-king — APPROVED** [review]
lgtm

**Review by tangkong — APPROVED** [review]
Seems good to me as well.  Let's move ahead

**Pull request merged**
